### PR TITLE
Migrated to Grails 3

### PR DESCRIPTION
**Pull request by rohitbishnoi**

### CODE REVIEW

**Comment by domurtag** [comment]
Thanks a lot for this. I will try to merge and release this later today. I haven't released a Grails 3 plugin before, so I can't be sure I'll be able to complete this today, but I'll do my best to get it published ASAP.

**Comment by domurtag** [comment]
I merged this on the command-line to the [grails3](https://github.com/domurtag/grails-simple-captcha/tree/grails3) branch. I'm getting an error when I try to publish it to bintray, but I'll leave a comment here once I've fixed this and it's released.

**Comment by rohitbishnoi** [comment]
Thank you very much Dónal for pushing this forward.

**Comment by domurtag** [comment]
@rohitbishnoi I haven't forgotten about this, but am struggling to figure out how to publish this to bintray. I've posted about the problem on [stackoverflow](http://stackoverflow.com/questions/30808826/nullpointerexception-when-publishing-a-grails-3-plugin). If you have time, you could try checking out the grails3 branch in my repo and publishing it to your own bintray account. There's a [guide here](https://medium.com/@benorama/how-to-publish-your-grails-3-plugin-to-bintray-c341b24f567d) that explains the process. You'll need to a couple of obvious changes in `build.gradle` to point to your bintray account instead of mine.

**Comment by rohitbishnoi** [comment]
Alright @domurtag I will try to do this today and let you know how it will go.

**Comment by domurtag** [comment]
Finally, it's published. Thanks again.
https://bintray.com/domurtag/plugins/domurtag.plugins%3Agrails-simple-captcha/

**Pull request closed without merging**
